title: Автоматизация торговли
optionalCategoryIndex: true
language: ru
supportedLanguages:
  - ru
properties: []
description: Создание, тестирование скриптов. Торговля агентами
style: green
group: tslab
order: 3
